contact_links:
  - name: Support Forums
    url: https://support.pods.io/
    about: Your questions may already be answered in our Forums.
  - name: Live Community Slack Chat
    url: https://support.pods.io/chat/
    about: You may find it helpful to join our Live Community Slack Chat to share ideas or ask questions.
