name: Generate Translations
on: workflow_dispatch
jobs:
  generate-translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress POT/PO/MO Generator
      uses: strangerstudios/action-wp-pot-po-mo-generator@main
      with:
        generate_pot: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
